# Generated by Django 4.2.6 on 2023-10-10 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('AT_code', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('X', models.DecimalField(decimal_places=14, max_digits=22)),
                ('Y', models.DecimalField(decimal_places=14, max_digits=22)),
                ('Z', models.DecimalField(decimal_places=14, max_digits=22)),
                ('MSE', models.DecimalField(decimal_places=2, max_digits=12)),
                ('PIT_code', models.CharField(max_length=16)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('species', models.CharField(max_length=12)),
                ('detection_time', models.DateTimeField(blank=True, null=True)),
                ('antenna_group_name', models.CharField(blank=True, max_length=50, null=True)),
                ('collection_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FishPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishdb.fish')),
            ],
        ),
    ]
