# Generated by Django 4.2.6 on 2023-10-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('AT_code', models.CharField(max_length=12)),
                ('X', models.DecimalField(decimal_places=10, max_digits=12)),
                ('Y', models.DecimalField(decimal_places=10, max_digits=12)),
                ('Z', models.DecimalField(decimal_places=10, max_digits=12)),
                ('MSE', models.DecimalField(decimal_places=2, max_digits=12)),
                ('PIT_code', models.CharField(max_length=16)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('species', models.CharField(max_length=12)),
                ('detection_time', models.DateTimeField(blank=True)),
                ('antenna_group_name', models.CharField(blank=True, max_length=50)),
                ('collection_status', models.BooleanField()),
            ],
        ),
    ]
