# Generated by Django 4.2.6 on 2023-10-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishposition',
            name='MSE',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fishposition',
            name='Z',
            field=models.DecimalField(decimal_places=14, default=0.0, max_digits=22),
        ),
        migrations.AlterField(
            model_name='fishposition',
            name='X',
            field=models.DecimalField(decimal_places=14, max_digits=22),
        ),
        migrations.AlterField(
            model_name='fishposition',
            name='Y',
            field=models.DecimalField(decimal_places=14, max_digits=22),
        ),
    ]
