# Generated by Django 4.2.6 on 2023-10-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0002_alter_fish_x_alter_fish_y_alter_fish_z'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='X',
            field=models.DecimalField(decimal_places=14, max_digits=22),
        ),
        migrations.AlterField(
            model_name='fish',
            name='Y',
            field=models.DecimalField(decimal_places=14, max_digits=22),
        ),
        migrations.AlterField(
            model_name='fish',
            name='Z',
            field=models.DecimalField(decimal_places=14, max_digits=22),
        ),
    ]
