# Generated by Django 4.2.6 on 2023-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0003_alter_fish_x_alter_fish_y_alter_fish_z'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='detection_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
