# Generated by Django 4.2.6 on 2023-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0004_alter_fish_detection_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='antenna_group_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
